# Generated by Django 4.1.5 on 2023-02-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peaks", "0002_auto_20230206_1719"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="peak",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours",
                to="peaks.peak",
            ),
        ),
    ]
