# Generated by Django 4.1.5 on 2023-02-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peaks", "0002_auto_20230207_2039"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tour",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="tour",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="tour",
            name="heading",
            field=models.CharField(default="Was empty", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tour",
            name="peak",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tours",
                to="peaks.peak",
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="text",
            field=models.TextField(),
        ),
    ]
