# Generated by Django 4.1.5 on 2023-02-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("peaks", "0003_alter_tour_options_alter_tour_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="peaks.tour",
                    ),
                ),
            ],
        ),
    ]
