# Generated by Django 4.1.5 on 2023-02-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peaks", "0007_grade_tag_tour_grade_tour_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=65),
        ),
    ]
