# Generated by Django 4.1.5 on 2023-02-22 08:30

# Add tags and grades to Database

# python manage.py makemigrations peaks --empty

from django.db import migrations
from django.utils.text import slugify

def tag_data(apps, schema_editor):
    Tag = apps.get_model("peaks", "Tag")
    Grade = apps.get_model("peaks", "Grade")

    tags = [
        "Climbing",
        "Ice",
        "Alpine",
        "Hiking",
        "Glacier",
        "Via Ferrata",
        "Ski Tour",
        "Snow Shoe",
        "Winter",
        "Snow",
        "Panorama",
        "Ridge",
    ]

    grades = [
        ("Easy Hiking", "Easy walking terrain"),
        ("Mountain Hiking", "Walking terrain, steep in parts"),
        ("Alpine Walking", "Walking in exposed terrain, rocky slopes, firn slopes"),
        ("Not very hard", "Mountaineering, some climbing in grade II, few crevasses"),
        ("Fairly hard", "Longer climbing sections up to grade III, many crevasses"),
        ("Hard", "Long climbing sections IV+, many crevasses, problematic navigation"),
        ("Very Hard", "Persistently challanging climbing with grade V+"),
        ("Extremely Hard", "Wall climbing, ice climbing etc. in grade VI+"),
    ]

    for t in tags:
        slug = slugify(t)
        tag = Tag(name=t, slug=slug)
        tag.save()

    for g in grades:
        grade = Grade(name=g[0], description=g[1])
        grade.save()

class Migration(migrations.Migration):
    dependencies = [
        ("peaks", "0008_tag_slug"),
    ]

    operations = [
        migrations.RunPython(tag_data),
    ]
